# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

AllCops:
  TargetRubyVersion: 2.6
  # 自動生成されるものは除外する
  Exclude:
    - "node_modules/**/*"
    - "db/*schema.rb"

# Hashの書き方はtableを許可
Layout/AlignHash:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Metrics/AbcSize:
  Max: 18

# TODO: 140はさすがに緩いので調整する。80くらいにしたい
Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb" # migrateは長くても許容する

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# namespaceを作ると階層が深くなるのでfalseにする
Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

# lambda は -> にする
Style/Lambda:
  EnforcedStyle: literal

# --------------------------------------------------------------
# TODO: 以下、一旦はオフにするもので検討したい
# --------------------------------------------------------------
Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# TODO: ' にするか " はどちらにするのかは意識あわせたい
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

