version: '3'

services:
  web: &web
    build:
      context: .
      dockerfile: docker/development/rails/Dockerfile
    volumes:
      - bundler:/usr/local/bundle:cached
      - .:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules:cached
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
  nginx:
    build:
      context: docker/development/nginx
    volumes:
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/development/nginx/ssl:/etc/nginx/ssl
    ports:
      - 443:443
    links:
      - web

volumes:
  bundler: {}
  node_modules: {}
  db: {}
